### ISSUE TITLE
handling the bad sequence of events

### ISSUE THREAD

**Issue by craftyguy** [wangp/plugsink#1]
I was thinking about this (the "bad sequence of events" from the readme...) some, maybe one way to deal with it is to prevent any mass-deletion-marking if all contents of the folder are involved, or if the number of changes exceeds some threshold (like, 80% of folder contents? 80% is just tossed out arbitrarily, could be anything, even user configurable). Then have a --force option to allow overriding the check in the case where a user really does want to expunge every mail from an entire imap folder.

**Comment by wangp** [comment]
Thanks for the reminder.

I think what I'll do is this. By default, it will refuse to sync if the local mailbox has too many deleted files. To continue regardless, you'll need to pass a command line option, `--allow-mass-delete <int>`, and that option will disable repeated synchronisation.

**Comment by wangp** [comment]
This is on master now.
