### ISSUE TITLE
Need a new name

### ISSUE THREAD

**Issue by wangp** [wangp/plugsink#2]
plugsink was a joke name.

**Comment by craftyguy** [comment]
out of curiosity, where does the name "bower" come from? (your email reader project, for those following along)

**Comment by wangp** [comment]
It refers to the bowers created by [bowerbirds](https://en.wikipedia.org/wiki/Bowerbird). There's no particular significance to the name. It was short and didn't clash with another software project (until the JS package manager came along). I didn't want another lame notmuch pun.
